spring:
  datasource:
    url: jdbc:mysql://localhost:3306/x-file-storage?allowPublicKeyRetrieval=true&useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=Asia/Shanghai&zeroDateTimeBehavior=convertToNull
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
dromara:
  x-file-storage: #文件存储配置
    default-platform: minio-1 #默认使用的存储平台
    thumbnail-suffix: ".min.jpg" #缩略图后缀，例如【.min.jpg】【.png】
    #对应平台的配置写在这里，注意缩进要对齐
    #阿里云
    aliyun-oss:
      - platform: aliyun-oss-1 # 存储平台标识
        enable-storage: true  # 启用存储
        access-key: ???
        secret-key: ???
        end-point: oss-cn-beijing.aliyuncs.com
        bucket-name: fx-blog-images
        domain: https://fx-blog-images.oss-cn-beijing.aliyuncs.com/ # 访问域名，注意“/”结尾，例如：https://abc.oss-cn-shanghai.aliyuncs.com/
        base-path: java/x-file-storage/ # 基础路径
    #华为云
    huawei-obs:
      - platform: huawei-obs-1 # 存储平台标识
        enable-storage: false  # 启用存储
        access-key: ??
        secret-key: ??
        end-point: ??
        bucket-name: ??
        domain: ?? # 访问域名，注意“/”结尾，例如：http://abc.obs.com/
        base-path: test/ # 基础路径
    #腾讯云
    tencent-cos:
      - platform: tencent-cos-1 # 存储平台标识
        enable-storage: false  # 启用存储
        secret-id: ??
        secret-key: ??
        region: ?? #存仓库所在地域
        bucket-name: ??
        domain: ?? # 访问域名，注意“/”结尾，例如：https://abc.cos.ap-nanjing.myqcloud.com/
        base-path: test/ # 基础路径
    #minio
    minio:
      - platform: minio-1 # 存储平台标识
        enable-storage: true  # 启用存储
        access-key: ???
        secret-key: ???
        end-point: https://toss.hevision.com
        bucket-name: openapi-client
        domain: https://toss.hevision.com/openapi-client/ # 访问域名，注意“/”结尾，例如：http://minio.abc.com/abc/
        base-path: x-file-storage/ # 基础路径
    #amazon s3
    amazon-s3: # 0.0.7 及以前的版本，配置名称是：aws-s3
      - platform: amazon-s3-1 # 存储平台标识
        enable-storage: true  # 启用存储
        access-key: ???
        secret-key: ???
        region: ?? # 与 end-point 参数至少填一个
        end-point: oss.xyclouds.cn:12001 # 与 region 参数至少填一个
        bucket-name: 012-test-openapi-data
        domain: https://oss.xyclouds.cn:12001/ # 访问域名，注意“/”结尾，例如：https://abc.hn-bkt.clouddn.com/
        base-path: s3/ # 基础路径
    #本地
    local-plus:
      - platform: local-plus-1 # 存储平台标识
        enable-storage: false  #启用存储
        enable-access: true #启用访问（线上请使用 Nginx 配置，效率更高）
        domain: "" # 访问域名，例如：“http://127.0.0.1:8030/local-plus/”，注意后面要和 path-patterns 保持一致，“/”结尾，本地存储建议使用相对路径，方便后期更换域名
        base-path: local-plus/ # 基础路径
        path-patterns: /local-plus/** # 访问路径
        storage-path: D:/Temp/ # 存储路径
